# -*- coding: utf-8 -*-
"""Bioinformatics_assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11fuZEE-YvbseRg1nY9XX3m_ZdwVqIzeM
"""

import numpy as np
import pandas as pd
from random import choice, choices, randrange

def needleman_wunsch(first, second, match=1, mismatch=-1, gap=-1):
    tab = np.full((len(second) + 2, len(first) + 2), ' ', dtype=object)
    tab[0, 2:] = first
    tab[1, 1:] = list(range(0, -len(first) - 1, -1))
    tab[2:, 0] = second
    tab[1:, 1] = list(range(0, -len(second) - 1, -1))
    is_equal = {True: match, False: mismatch}
    for f in range(2, len(first) + 2):
        for s in range(2, len(second) + 2):
            tab[s, f] = max(tab[s - 1][f - 1] + is_equal[first[f - 2] == second[s - 2]],
                            tab[s - 1][f] + gap,
                            tab[s][f - 1] + gap)
    return tab


def mutate(seq, rounds=3):
    mutate_seq = seq.copy()
    for change in choices((deletion, insertion), k=rounds):
        pos = randrange(len(mutate_seq))
        change(mutate_seq, pos)
    return mutate_seq


def deletion(seq, idx):
    seq.pop(idx)


def insertion(seq, idx):
    seq.insert(idx, choice("ACTG".replace(seq[idx], "")))


def main():
    first_seq = choices("ACTG", k=5)
    second_seq = mutate(first_seq)
    data = needleman_wunsch(first_seq, second_seq)
    print(pd.DataFrame(data))


if __name__ == '__main__':
    main()